# Generated by Django 6.0 on 2025-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_patient_status_patient_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20),
        ),
    ]
